[36m[2023-08-31 13:45:43 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-08-31 13:45:43 DEBUG] [cli:115][39m Running command 'run'
[36m[2023-08-31 13:45:43 DEBUG] [cli:119][39m Using settings file '/Users/collinsorighose/.chaostoolkit/settings.yaml'
[36m[2023-08-31 13:45:43 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at '/Users/collinsorighose/.chaostoolkit/settings.yaml'.
[36m[2023-08-31 13:45:43 DEBUG] [__init__:450][39m No controls to apply on 'loader'
[36m[2023-08-31 13:45:43 DEBUG] [__init__:450][39m No controls to apply on 'loader'
[36m[2023-08-31 13:45:43 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-08-31 13:45:43 DEBUG] [caching:35][39m Cached 1 activities
[32m[2023-08-31 13:45:43 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2023-08-31 13:45:43 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-08-31 13:45:43 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-08-31 13:45:43 DEBUG] [secret:103][39m Done loading secrets
[32m[2023-08-31 13:45:43 INFO] [experiment:109][39m Experiment looks valid
[36m[2023-08-31 13:45:43 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-08-31 13:45:43 DEBUG] [cli:314][39m Runtime strategies: hypothesis - default / rollbacks - default
[36m[2023-08-31 13:45:43 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-08-31 13:45:43 DEBUG] [caching:35][39m Cached 1 activities
[36m[2023-08-31 13:45:43 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-08-31 13:45:43 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-08-31 13:45:43 DEBUG] [secret:103][39m Done loading secrets
[36m[2023-08-31 13:45:43 DEBUG] [configuration:160][39m Loading dynamic configuration...
[32m[2023-08-31 13:45:43 INFO] [run:369][39m Running experiment: delete-s3-object
[36m[2023-08-31 13:45:43 DEBUG] [__init__:64][39m Initializing controls
[32m[2023-08-31 13:45:43 INFO] [run:396][39m Steady-state strategy: default
[32m[2023-08-31 13:45:43 INFO] [run:400][39m Rollbacks strategy: default
[32m[2023-08-31 13:45:43 INFO] [run:408][39m No steady state hypothesis defined. That's ok, just exploring.
[36m[2023-08-31 13:45:43 DEBUG] [__init__:450][39m No controls to apply on 'experiment'
[32m[2023-08-31 13:45:43 INFO] [run:684][39m Playing your experiment's method now...
[36m[2023-08-31 13:45:43 DEBUG] [__init__:450][39m No controls to apply on 'method'
[36m[2023-08-31 13:45:43 DEBUG] [__init__:450][39m No controls to apply on 'activity'
[32m[2023-08-31 13:45:43 INFO] [activity:215][39m Action: delete-object
[36m[2023-08-31 13:45:43 DEBUG] [python:33][39m Activity 'delete-object' loaded from '/Users/collinsorighose/opt/anaconda3/envs/demo/lib/python3.11/site-packages/chaosaws/s3/actions.py'
[36m[2023-08-31 13:45:43 DEBUG] [__init__:76][39m Using AWS region 'eu-west-2'
[36m[2023-08-31 13:45:43 DEBUG] [activity:294][39m Activity failed
    Traceback (most recent call last):
      File "/Users/collinsorighose/opt/anaconda3/envs/demo/lib/python3.11/site-packages/chaoslib/provider/python.py", line 56, in run_python_activity
        return func(**arguments)
               ^^^^^^^^^^^^^^^^^
      File "/Users/collinsorighose/opt/anaconda3/envs/demo/lib/python3.11/site-packages/chaosaws/s3/actions.py", line 26, in delete_object
        client = aws_client("s3", configuration, secrets)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/collinsorighose/opt/anaconda3/envs/demo/lib/python3.11/site-packages/chaosaws/__init__.py", line 82, in aws_client
        boto3.setup_default_session(profile_name=aws_profile_name, **params)
      File "/Users/collinsorighose/opt/anaconda3/envs/demo/lib/python3.11/site-packages/boto3/__init__.py", line 34, in setup_default_session
        DEFAULT_SESSION = Session(**kwargs)
                          ^^^^^^^^^^^^^^^^^
      File "/Users/collinsorighose/opt/anaconda3/envs/demo/lib/python3.11/site-packages/boto3/session.py", line 90, in __init__
        self._setup_loader()
      File "/Users/collinsorighose/opt/anaconda3/envs/demo/lib/python3.11/site-packages/boto3/session.py", line 131, in _setup_loader
        self._loader = self._session.get_component('data_loader')
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/collinsorighose/opt/anaconda3/envs/demo/lib/python3.11/site-packages/botocore/session.py", line 796, in get_component
        return self._components.get_component(name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/collinsorighose/opt/anaconda3/envs/demo/lib/python3.11/site-packages/botocore/session.py", line 1108, in get_component
        self._components[name] = factory()
                                 ^^^^^^^^^
      File "/Users/collinsorighose/opt/anaconda3/envs/demo/lib/python3.11/site-packages/botocore/session.py", line 193, in <lambda>
        lambda: create_loader(self.get_config_variable('data_path')),
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/collinsorighose/opt/anaconda3/envs/demo/lib/python3.11/site-packages/botocore/session.py", line 317, in get_config_variable
        return self.get_component('config_store').get_config_variable(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/collinsorighose/opt/anaconda3/envs/demo/lib/python3.11/site-packages/botocore/configprovider.py", line 426, in get_config_variable
        return provider.provide()
               ^^^^^^^^^^^^^^^^^^
      File "/Users/collinsorighose/opt/anaconda3/envs/demo/lib/python3.11/site-packages/botocore/configprovider.py", line 628, in provide
        value = provider.provide()
                ^^^^^^^^^^^^^^^^^^
      File "/Users/collinsorighose/opt/anaconda3/envs/demo/lib/python3.11/site-packages/botocore/configprovider.py", line 718, in provide
        scoped_config = self._session.get_scoped_config()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/collinsorighose/opt/anaconda3/envs/demo/lib/python3.11/site-packages/botocore/session.py", line 416, in get_scoped_config
        raise ProfileNotFound(profile=profile_name)
    botocore.exceptions.ProfileNotFound: The config profile (bravo) could not be found
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/collinsorighose/opt/anaconda3/envs/demo/lib/python3.11/site-packages/chaoslib/activity.py", line 287, in run_activity
        result = run_python_activity(activity, configuration, secrets)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/collinsorighose/opt/anaconda3/envs/demo/lib/python3.11/site-packages/chaoslib/provider/python.py", line 58, in run_python_activity
        raise ActivityFailed(
      File "/Users/collinsorighose/opt/anaconda3/envs/demo/lib/python3.11/site-packages/chaoslib/provider/python.py", line 56, in run_python_activity
        return func(**arguments)
               ^^^^^^^^^^^^^^^^^
      File "/Users/collinsorighose/opt/anaconda3/envs/demo/lib/python3.11/site-packages/chaosaws/s3/actions.py", line 26, in delete_object
        client = aws_client("s3", configuration, secrets)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/collinsorighose/opt/anaconda3/envs/demo/lib/python3.11/site-packages/chaosaws/__init__.py", line 82, in aws_client
        boto3.setup_default_session(profile_name=aws_profile_name, **params)
      File "/Users/collinsorighose/opt/anaconda3/envs/demo/lib/python3.11/site-packages/boto3/__init__.py", line 34, in setup_default_session
        DEFAULT_SESSION = Session(**kwargs)
                          ^^^^^^^^^^^^^^^^^
      File "/Users/collinsorighose/opt/anaconda3/envs/demo/lib/python3.11/site-packages/boto3/session.py", line 90, in __init__
        self._setup_loader()
      File "/Users/collinsorighose/opt/anaconda3/envs/demo/lib/python3.11/site-packages/boto3/session.py", line 131, in _setup_loader
        self._loader = self._session.get_component('data_loader')
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/collinsorighose/opt/anaconda3/envs/demo/lib/python3.11/site-packages/botocore/session.py", line 796, in get_component
        return self._components.get_component(name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/collinsorighose/opt/anaconda3/envs/demo/lib/python3.11/site-packages/botocore/session.py", line 1108, in get_component
        self._components[name] = factory()
                                 ^^^^^^^^^
      File "/Users/collinsorighose/opt/anaconda3/envs/demo/lib/python3.11/site-packages/botocore/session.py", line 193, in <lambda>
        lambda: create_loader(self.get_config_variable('data_path')),
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/collinsorighose/opt/anaconda3/envs/demo/lib/python3.11/site-packages/botocore/session.py", line 317, in get_config_variable
        return self.get_component('config_store').get_config_variable(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/collinsorighose/opt/anaconda3/envs/demo/lib/python3.11/site-packages/botocore/configprovider.py", line 426, in get_config_variable
        return provider.provide()
               ^^^^^^^^^^^^^^^^^^
      File "/Users/collinsorighose/opt/anaconda3/envs/demo/lib/python3.11/site-packages/botocore/configprovider.py", line 628, in provide
        value = provider.provide()
                ^^^^^^^^^^^^^^^^^^
      File "/Users/collinsorighose/opt/anaconda3/envs/demo/lib/python3.11/site-packages/botocore/configprovider.py", line 718, in provide
        scoped_config = self._session.get_scoped_config()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/collinsorighose/opt/anaconda3/envs/demo/lib/python3.11/site-packages/botocore/session.py", line 416, in get_scoped_config
        raise ProfileNotFound(profile=profile_name)
    chaoslib.exceptions.ActivityFailed: botocore.exceptions.ProfileNotFound: The config profile (bravo) could not be found
[31m[2023-08-31 13:45:43 ERROR] [activity:245][39m   => failed: botocore.exceptions.ProfileNotFound: The config profile (bravo) could not be found
[36m[2023-08-31 13:45:43 DEBUG] [__init__:450][39m No controls to apply on 'activity'
[36m[2023-08-31 13:45:43 DEBUG] [__init__:450][39m No controls to apply on 'method'
[32m[2023-08-31 13:45:43 INFO] [run:964][39m Let's rollback...
[36m[2023-08-31 13:45:43 DEBUG] [__init__:450][39m No controls to apply on 'rollback'
[32m[2023-08-31 13:45:43 INFO] [rollback:31][39m No declared rollbacks, let's move on.
[36m[2023-08-31 13:45:43 DEBUG] [__init__:450][39m No controls to apply on 'rollback'
[32m[2023-08-31 13:45:43 INFO] [run:515][39m Experiment ended with status: completed
[36m[2023-08-31 13:45:43 DEBUG] [__init__:450][39m No controls to apply on 'experiment'
[36m[2023-08-31 13:45:43 DEBUG] [__init__:103][39m Cleaning up controls
[36m[2023-08-31 13:45:43 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-08-31 13:46:01 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-08-31 13:46:01 DEBUG] [cli:115][39m Running command 'run'
[36m[2023-08-31 13:46:01 DEBUG] [cli:119][39m Using settings file '/Users/collinsorighose/.chaostoolkit/settings.yaml'
[36m[2023-08-31 13:46:02 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at '/Users/collinsorighose/.chaostoolkit/settings.yaml'.
[36m[2023-08-31 13:46:02 DEBUG] [__init__:450][39m No controls to apply on 'loader'
[36m[2023-08-31 13:46:02 DEBUG] [__init__:450][39m No controls to apply on 'loader'
[36m[2023-08-31 13:46:02 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-08-31 13:46:02 DEBUG] [caching:35][39m Cached 1 activities
[32m[2023-08-31 13:46:02 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2023-08-31 13:46:02 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-08-31 13:46:02 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-08-31 13:46:02 DEBUG] [secret:103][39m Done loading secrets
[32m[2023-08-31 13:46:02 INFO] [experiment:109][39m Experiment looks valid
[36m[2023-08-31 13:46:02 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-08-31 13:46:02 DEBUG] [cli:314][39m Runtime strategies: hypothesis - default / rollbacks - default
[36m[2023-08-31 13:46:02 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-08-31 13:46:02 DEBUG] [caching:35][39m Cached 1 activities
[36m[2023-08-31 13:46:02 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-08-31 13:46:02 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-08-31 13:46:02 DEBUG] [secret:103][39m Done loading secrets
[36m[2023-08-31 13:46:02 DEBUG] [configuration:160][39m Loading dynamic configuration...
[32m[2023-08-31 13:46:02 INFO] [run:369][39m Running experiment: delete-s3-object
[36m[2023-08-31 13:46:02 DEBUG] [__init__:64][39m Initializing controls
[32m[2023-08-31 13:46:02 INFO] [run:396][39m Steady-state strategy: default
[32m[2023-08-31 13:46:02 INFO] [run:400][39m Rollbacks strategy: default
[32m[2023-08-31 13:46:02 INFO] [run:408][39m No steady state hypothesis defined. That's ok, just exploring.
[36m[2023-08-31 13:46:02 DEBUG] [__init__:450][39m No controls to apply on 'experiment'
[32m[2023-08-31 13:46:02 INFO] [run:684][39m Playing your experiment's method now...
[36m[2023-08-31 13:46:02 DEBUG] [__init__:450][39m No controls to apply on 'method'
[36m[2023-08-31 13:46:02 DEBUG] [__init__:450][39m No controls to apply on 'activity'
[32m[2023-08-31 13:46:02 INFO] [activity:215][39m Action: delete-object
[36m[2023-08-31 13:46:02 DEBUG] [python:33][39m Activity 'delete-object' loaded from '/Users/collinsorighose/opt/anaconda3/envs/demo/lib/python3.11/site-packages/chaosaws/s3/actions.py'
[36m[2023-08-31 13:46:02 DEBUG] [__init__:76][39m Using AWS region 'eu-west-2'
[36m[2023-08-31 13:46:02 DEBUG] [__init__:85][39m Client will be using profile 'default' from boto3 session
[36m[2023-08-31 13:46:03 DEBUG] [activity:239][39m   => succeeded without any result value
[36m[2023-08-31 13:46:03 DEBUG] [__init__:450][39m No controls to apply on 'activity'
[36m[2023-08-31 13:46:03 DEBUG] [__init__:450][39m No controls to apply on 'method'
[32m[2023-08-31 13:46:03 INFO] [run:964][39m Let's rollback...
[36m[2023-08-31 13:46:03 DEBUG] [__init__:450][39m No controls to apply on 'rollback'
[32m[2023-08-31 13:46:03 INFO] [rollback:31][39m No declared rollbacks, let's move on.
[36m[2023-08-31 13:46:03 DEBUG] [__init__:450][39m No controls to apply on 'rollback'
[32m[2023-08-31 13:46:03 INFO] [run:515][39m Experiment ended with status: completed
[36m[2023-08-31 13:46:03 DEBUG] [__init__:450][39m No controls to apply on 'experiment'
[36m[2023-08-31 13:46:03 DEBUG] [__init__:103][39m Cleaning up controls
[36m[2023-08-31 13:46:03 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-08-31 13:58:58 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-08-31 13:58:58 DEBUG] [cli:115][39m Running command 'run'
[36m[2023-08-31 13:58:58 DEBUG] [cli:119][39m Using settings file '/Users/collinsorighose/.chaostoolkit/settings.yaml'
[36m[2023-08-31 13:58:59 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at '/Users/collinsorighose/.chaostoolkit/settings.yaml'.
[36m[2023-08-31 13:58:59 DEBUG] [__init__:450][39m No controls to apply on 'loader'
[36m[2023-08-31 13:58:59 DEBUG] [__init__:450][39m No controls to apply on 'loader'
[36m[2023-08-31 13:58:59 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-08-31 13:58:59 DEBUG] [caching:35][39m Cached 1 activities
[32m[2023-08-31 13:58:59 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2023-08-31 13:58:59 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-08-31 13:58:59 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-08-31 13:58:59 DEBUG] [secret:103][39m Done loading secrets
[32m[2023-08-31 13:58:59 INFO] [experiment:109][39m Experiment looks valid
[36m[2023-08-31 13:58:59 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-08-31 13:58:59 DEBUG] [cli:314][39m Runtime strategies: hypothesis - default / rollbacks - default
[36m[2023-08-31 13:58:59 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-08-31 13:58:59 DEBUG] [caching:35][39m Cached 1 activities
[36m[2023-08-31 13:58:59 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-08-31 13:58:59 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-08-31 13:58:59 DEBUG] [secret:103][39m Done loading secrets
[36m[2023-08-31 13:58:59 DEBUG] [configuration:160][39m Loading dynamic configuration...
[32m[2023-08-31 13:58:59 INFO] [run:369][39m Running experiment: delete-s3-object
[36m[2023-08-31 13:58:59 DEBUG] [__init__:64][39m Initializing controls
[32m[2023-08-31 13:58:59 INFO] [run:396][39m Steady-state strategy: default
[32m[2023-08-31 13:58:59 INFO] [run:400][39m Rollbacks strategy: default
[32m[2023-08-31 13:58:59 INFO] [run:408][39m No steady state hypothesis defined. That's ok, just exploring.
[36m[2023-08-31 13:58:59 DEBUG] [__init__:450][39m No controls to apply on 'experiment'
[32m[2023-08-31 13:58:59 INFO] [run:684][39m Playing your experiment's method now...
[36m[2023-08-31 13:58:59 DEBUG] [__init__:450][39m No controls to apply on 'method'
[36m[2023-08-31 13:58:59 DEBUG] [__init__:450][39m No controls to apply on 'activity'
[32m[2023-08-31 13:58:59 INFO] [activity:215][39m Action: delete-object
[36m[2023-08-31 13:58:59 DEBUG] [python:33][39m Activity 'delete-object' loaded from '/Users/collinsorighose/opt/anaconda3/envs/demo/lib/python3.11/site-packages/chaosaws/s3/actions.py'
[36m[2023-08-31 13:58:59 DEBUG] [__init__:76][39m Using AWS region 'eu-west-2'
[36m[2023-08-31 13:58:59 DEBUG] [__init__:85][39m Client will be using profile 'default' from boto3 session
[36m[2023-08-31 13:59:01 DEBUG] [activity:239][39m   => succeeded without any result value
[36m[2023-08-31 13:59:01 DEBUG] [__init__:450][39m No controls to apply on 'activity'
[36m[2023-08-31 13:59:01 DEBUG] [__init__:450][39m No controls to apply on 'method'
[32m[2023-08-31 13:59:01 INFO] [run:964][39m Let's rollback...
[36m[2023-08-31 13:59:01 DEBUG] [__init__:450][39m No controls to apply on 'rollback'
[32m[2023-08-31 13:59:01 INFO] [rollback:31][39m No declared rollbacks, let's move on.
[36m[2023-08-31 13:59:01 DEBUG] [__init__:450][39m No controls to apply on 'rollback'
[32m[2023-08-31 13:59:01 INFO] [run:515][39m Experiment ended with status: completed
[36m[2023-08-31 13:59:01 DEBUG] [__init__:450][39m No controls to apply on 'experiment'
[36m[2023-08-31 13:59:01 DEBUG] [__init__:103][39m Cleaning up controls
[36m[2023-08-31 13:59:01 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-08-31 13:59:34 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-08-31 13:59:34 DEBUG] [cli:115][39m Running command 'run'
[36m[2023-08-31 13:59:34 DEBUG] [cli:119][39m Using settings file '/Users/collinsorighose/.chaostoolkit/settings.yaml'
[36m[2023-08-31 13:59:34 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at '/Users/collinsorighose/.chaostoolkit/settings.yaml'.
[36m[2023-08-31 13:59:34 DEBUG] [__init__:450][39m No controls to apply on 'loader'
[36m[2023-08-31 13:59:34 DEBUG] [__init__:450][39m No controls to apply on 'loader'
[36m[2023-08-31 13:59:34 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-08-31 13:59:34 DEBUG] [caching:35][39m Cached 1 activities
[32m[2023-08-31 13:59:34 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2023-08-31 13:59:34 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-08-31 13:59:34 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-08-31 13:59:34 DEBUG] [secret:103][39m Done loading secrets
[32m[2023-08-31 13:59:34 INFO] [experiment:109][39m Experiment looks valid
[36m[2023-08-31 13:59:34 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-08-31 13:59:34 DEBUG] [cli:314][39m Runtime strategies: hypothesis - default / rollbacks - default
[36m[2023-08-31 13:59:34 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-08-31 13:59:34 DEBUG] [caching:35][39m Cached 1 activities
[36m[2023-08-31 13:59:34 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-08-31 13:59:34 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-08-31 13:59:34 DEBUG] [secret:103][39m Done loading secrets
[36m[2023-08-31 13:59:34 DEBUG] [configuration:160][39m Loading dynamic configuration...
[32m[2023-08-31 13:59:34 INFO] [run:369][39m Running experiment: delete-s3-object
[36m[2023-08-31 13:59:34 DEBUG] [__init__:64][39m Initializing controls
[32m[2023-08-31 13:59:34 INFO] [run:396][39m Steady-state strategy: default
[32m[2023-08-31 13:59:34 INFO] [run:400][39m Rollbacks strategy: default
[32m[2023-08-31 13:59:34 INFO] [run:408][39m No steady state hypothesis defined. That's ok, just exploring.
[36m[2023-08-31 13:59:34 DEBUG] [__init__:450][39m No controls to apply on 'experiment'
[32m[2023-08-31 13:59:34 INFO] [run:684][39m Playing your experiment's method now...
[36m[2023-08-31 13:59:34 DEBUG] [__init__:450][39m No controls to apply on 'method'
[36m[2023-08-31 13:59:34 DEBUG] [__init__:450][39m No controls to apply on 'activity'
[32m[2023-08-31 13:59:34 INFO] [activity:215][39m Action: delete-object
[36m[2023-08-31 13:59:34 DEBUG] [python:33][39m Activity 'delete-object' loaded from '/Users/collinsorighose/opt/anaconda3/envs/demo/lib/python3.11/site-packages/chaosaws/s3/actions.py'
[36m[2023-08-31 13:59:34 DEBUG] [__init__:76][39m Using AWS region 'eu-west-2'
[36m[2023-08-31 13:59:34 DEBUG] [__init__:85][39m Client will be using profile 'default' from boto3 session
[36m[2023-08-31 13:59:35 DEBUG] [activity:239][39m   => succeeded without any result value
[36m[2023-08-31 13:59:35 DEBUG] [__init__:450][39m No controls to apply on 'activity'
[36m[2023-08-31 13:59:35 DEBUG] [__init__:450][39m No controls to apply on 'method'
[32m[2023-08-31 13:59:35 INFO] [run:964][39m Let's rollback...
[36m[2023-08-31 13:59:35 DEBUG] [__init__:450][39m No controls to apply on 'rollback'
[32m[2023-08-31 13:59:35 INFO] [rollback:31][39m No declared rollbacks, let's move on.
[36m[2023-08-31 13:59:35 DEBUG] [__init__:450][39m No controls to apply on 'rollback'
[32m[2023-08-31 13:59:35 INFO] [run:515][39m Experiment ended with status: completed
[36m[2023-08-31 13:59:35 DEBUG] [__init__:450][39m No controls to apply on 'experiment'
[36m[2023-08-31 13:59:35 DEBUG] [__init__:103][39m Cleaning up controls
[36m[2023-08-31 13:59:35 DEBUG] [caching:42][39m Clearing activities cache
